export type Provider = {
  name: string
  fee: string
  feeUSD?: number       // numeric fee in sending currency for sorting
  exchangeRateNote: string
  estimatedKES: string  // what KES 100 USD/GBP/AED/EUR delivers approx
  speed: string
  deliveryMethods: string[]
  rating: number
  promoNote?: string
  affiliateNote?: string
  bestFor: string
}

export type Corridor = {
  slug: string
  country: string
  countryCode: string
  currency: string
  currencyCode: string
  currencySymbol: string
  sampleAmount: number  // e.g. 100
  diasporaSize: string
  remittanceVolume: string
  popularCities: string[]
  providers: Provider[]
  howToSteps: string[]
  taxNote: string
  regulatoryNote: string
  faqs: { q: string; a: string }[]
  tips: string[]
}

export const corridors: Corridor[] = [
  // ── UK ──────────────────────────────────────────────────────────────────
  {
    slug: 'uk',
    country: 'United Kingdom',
    countryCode: 'GB',
    currency: 'British Pound',
    currencyCode: 'GBP',
    currencySymbol: '£',
    sampleAmount: 100,
    diasporaSize: '~100,000 Kenyans in the UK',
    remittanceVolume: 'One of Kenya\'s top 5 remittance corridors',
    popularCities: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Edinburgh'],
    providers: [
      {
        name: 'Sendwave',
        fee: 'Zero fees',
        feeUSD: 0,
        exchangeRateNote: 'Slight margin on mid-market rate (~0.5–1.5%)',
        estimatedKES: '~KES 16,800 per £100',
        speed: 'Instant to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account'],
        rating: 4.8,
        bestFor: 'Sending directly to M-Pesa with zero fees',
        promoNote: 'No fees, ever — Sendwave earns only on the exchange rate margin',
      },
      {
        name: 'Wise',
        fee: '~£0.60 + 0.47% on amount',
        feeUSD: 1.1,
        exchangeRateNote: 'Mid-market rate — the real exchange rate with no markup',
        estimatedKES: '~KES 16,950 per £100 (best rate)',
        speed: '1–2 hours (bank) / same day',
        deliveryMethods: ['Bank Account', 'M-Pesa'],
        rating: 4.7,
        bestFor: 'Best exchange rate for bank transfers',
      },
      {
        name: 'WorldRemit',
        fee: '£0.99–£2.99 fixed',
        feeUSD: 2.5,
        exchangeRateNote: '1–2% margin on mid-market rate',
        estimatedKES: '~KES 16,400 per £100',
        speed: 'Minutes to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account', 'Airtime Top-Up', 'Cash Pickup'],
        rating: 4.5,
        bestFor: 'Airtime top-up and cash pickup options',
      },
      {
        name: 'Remitly',
        fee: '£0–£3.99 (Express) / £0 (Economy)',
        feeUSD: 2.0,
        exchangeRateNote: '1–2% margin',
        estimatedKES: '~KES 16,300 per £100',
        speed: 'Minutes (Express) / 3–5 days (Economy)',
        deliveryMethods: ['M-Pesa', 'Bank Account'],
        rating: 4.6,
        bestFor: 'Economy rate for non-urgent large transfers',
      },
      {
        name: 'Mukuru',
        fee: '£1.50–£4.00',
        feeUSD: 2.5,
        exchangeRateNote: '1.5–2.5% margin',
        estimatedKES: '~KES 16,000 per £100',
        speed: 'Same day to next day',
        deliveryMethods: ['M-Pesa', 'Bank Account', 'Cash Pickup'],
        rating: 4.2,
        bestFor: 'Cash pickup in Nairobi and rural Kenya',
      },
      {
        name: 'Western Union',
        fee: '£2.90–£8.90',
        feeUSD: 6.0,
        exchangeRateNote: '3–5% margin on mid-market',
        estimatedKES: '~KES 15,400 per £100',
        speed: 'Minutes (cash) / Same day (M-Pesa)',
        deliveryMethods: ['Cash Pickup', 'M-Pesa', 'Bank Account'],
        rating: 3.7,
        bestFor: 'Cash pickup at agent network across Kenya',
        affiliateNote: 'Widely available but one of the more expensive options',
      },
    ],
    howToSteps: [
      'Compare providers above — for M-Pesa delivery, Sendwave or WorldRemit are typically fastest',
      'Download the provider\'s app (Sendwave, Wise, Remitly, or WorldRemit)',
      'Verify your identity with a UK ID (passport, driving licence) — one-time process',
      'Enter the recipient\'s Kenyan phone number or bank account details',
      'Enter the amount in GBP and confirm the exchange rate shown',
      'Pay via UK bank transfer, debit card, or Faster Payments',
      'Track your transfer — M-Pesa delivery is typically instant',
      'Recipient gets an M-Pesa notification or bank credit',
    ],
    taxNote: 'No UK tax on sending remittances. Amounts above £10,000 may require anti-money-laundering documentation.',
    regulatoryNote: 'All listed providers are FCA-regulated in the UK. Always use FCA-authorised services.',
    faqs: [
      {
        q: 'What is the cheapest way to send money from the UK to Kenya?',
        a: 'Sendwave charges zero fees and has competitive rates for M-Pesa delivery. For bank-to-bank transfers, Wise offers the mid-market rate with minimal fees — typically the best total cost for larger amounts.',
      },
      {
        q: 'How long does it take to send money from the UK to M-Pesa?',
        a: 'Sendwave and WorldRemit typically deliver to M-Pesa within minutes. Wise bank transfers take 1–2 hours. Economy rates on Remitly can take 3–5 days.',
      },
      {
        q: 'Is there a limit on how much I can send from the UK to Kenya?',
        a: 'Most providers allow up to £5,000–£10,000 per transaction without enhanced verification. Higher amounts require proof of source of funds. M-Pesa can receive up to KES 300,000 per transaction.',
      },
      {
        q: 'Do I need to declare money sent from the UK to Kenya?',
        a: 'You do not need to declare remittances in the UK. In Kenya, personal remittances are not taxed. Large commercial transfers may require CBK reporting.',
      },
      {
        q: 'Can I send from UK to a Kenyan bank account directly?',
        a: 'Yes — Wise, Remitly, and WorldRemit all support direct bank account delivery to Equity, KCB, Co-op, NCBA and other major Kenyan banks.',
      },
    ],
    tips: [
      'Send on weekdays during business hours for best exchange rates — spreads can widen on weekends',
      'Avoid airport or high-street bureaux de change — online providers are consistently cheaper',
      'Set up a rate alert on Wise or Remitly to be notified when the KES/GBP rate improves',
      'For regular monthly transfers, check if your provider offers a recurring transfer discount',
    ],
  },

  // ── USA ─────────────────────────────────────────────────────────────────
  {
    slug: 'usa',
    country: 'United States',
    countryCode: 'US',
    currency: 'US Dollar',
    currencyCode: 'USD',
    currencySymbol: '$',
    sampleAmount: 100,
    diasporaSize: '~100,000 Kenyans in the USA',
    remittanceVolume: 'Kenya\'s largest remittance corridor by volume',
    popularCities: ['New York', 'Atlanta', 'Dallas', 'Boston', 'Minneapolis', 'Houston'],
    providers: [
      {
        name: 'Sendwave',
        fee: 'Zero fees',
        feeUSD: 0,
        exchangeRateNote: '0.5–1.5% margin on mid-market',
        estimatedKES: '~KES 13,100 per $100',
        speed: 'Instant to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account'],
        rating: 4.9,
        bestFor: 'Zero-fee M-Pesa transfers — most popular in the USA diaspora',
        promoNote: 'Sendwave is the #1 rated remittance app for Kenya among US Kenyans',
      },
      {
        name: 'Wise',
        fee: '~$1.08 + 0.47%',
        feeUSD: 1.5,
        exchangeRateNote: 'Mid-market rate — no markup',
        estimatedKES: '~KES 13,250 per $100 (best rate)',
        speed: '2–24 hours',
        deliveryMethods: ['Bank Account', 'M-Pesa'],
        rating: 4.7,
        bestFor: 'Large transfers where exchange rate matters most',
      },
      {
        name: 'Remitly',
        fee: '$0–$3.99',
        feeUSD: 2.0,
        exchangeRateNote: '1–1.5% margin',
        estimatedKES: '~KES 12,900 per $100',
        speed: 'Minutes (Express) / 3–5 days (Economy)',
        deliveryMethods: ['M-Pesa', 'Bank Account', 'Cash Pickup'],
        rating: 4.6,
        bestFor: 'New users — first transfer often heavily discounted',
        promoNote: 'Often runs "first transfer free" promotions',
      },
      {
        name: 'WorldRemit',
        fee: '$1.99–$4.99',
        feeUSD: 3.5,
        exchangeRateNote: '1–2% margin',
        estimatedKES: '~KES 12,700 per $100',
        speed: 'Minutes to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account', 'Airtime Top-Up', 'Cash Pickup'],
        rating: 4.4,
        bestFor: 'Airtime top-ups and cash pickup',
      },
      {
        name: 'MoneyGram',
        fee: '$1.99–$9.99',
        feeUSD: 6.0,
        exchangeRateNote: '2–4% margin',
        estimatedKES: '~KES 12,400 per $100',
        speed: 'Minutes to hours',
        deliveryMethods: ['Cash Pickup', 'M-Pesa', 'Bank Account'],
        rating: 3.8,
        bestFor: 'In-person cash pickup at Kenyan agent locations',
      },
      {
        name: 'Western Union',
        fee: '$5–$15',
        feeUSD: 9.0,
        exchangeRateNote: '3–5% margin',
        estimatedKES: '~KES 11,800 per $100',
        speed: 'Minutes to same day',
        deliveryMethods: ['Cash Pickup', 'M-Pesa', 'Bank Account'],
        rating: 3.5,
        bestFor: 'Cash pickup at widespread agent network',
      },
    ],
    howToSteps: [
      'Download Sendwave, Remitly, or Wise — all work well from the USA to Kenya',
      'Create an account using your US phone number and email',
      'Verify your identity (US driver\'s licence, SSN last 4, or passport)',
      'Add your US bank account or debit card as the funding source',
      'Enter the recipient\'s Kenyan M-Pesa number or bank account',
      'Enter the amount in USD and review the KES amount they will receive',
      'Confirm and submit — M-Pesa deliveries arrive within minutes',
    ],
    taxNote: 'No US tax on personal remittances under the annual gift tax exclusion ($18,000 in 2026). Consult a tax advisor for amounts above this.',
    regulatoryNote: 'All listed providers are registered with FinCEN and licensed as Money Service Businesses (MSBs) in relevant US states.',
    faqs: [
      {
        q: 'What is the best app to send money from the USA to Kenya?',
        a: 'Sendwave is consistently rated #1 by the Kenyan diaspora in the US for zero fees and instant M-Pesa delivery. For larger amounts where the exchange rate matters more, Wise offers the mid-market rate.',
      },
      {
        q: 'How much does it cost to send $200 from the USA to Kenya?',
        a: 'With Sendwave — zero fee. With Wise — approximately $2.02 (fee) plus mid-market rate. With Remitly Express — approximately $3.99 fee. Always compare the total received amount in KES, not just the fee.',
      },
      {
        q: 'Can I send money from the USA to Kenya M-Pesa directly?',
        a: 'Yes — Sendwave, WorldRemit, and Remitly all offer direct delivery to M-Pesa numbers. The recipient gets an M-Pesa notification within minutes.',
      },
      {
        q: 'Is it safe to use Sendwave from the USA?',
        a: 'Yes — Sendwave (now owned by Wave) is licensed in all 50 US states and is one of the most trusted remittance apps for Africa. Used by hundreds of thousands of US Kenyans.',
      },
    ],
    tips: [
      'Sendwave has no fees — it\'s the default choice for most US Kenyans for M-Pesa transfers',
      'For amounts above $1,000, run a side-by-side comparison on Wise vs Sendwave — rate margins vary',
      'ACH bank transfers are cheaper than debit card funding — link your US bank account',
      'Some US states have specific money transmitter requirements — check your provider is licensed in your state',
    ],
  },

  // ── UAE ─────────────────────────────────────────────────────────────────
  {
    slug: 'uae',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    currency: 'UAE Dirham',
    currencyCode: 'AED',
    currencySymbol: 'AED',
    sampleAmount: 100,
    diasporaSize: '~50,000 Kenyans in UAE',
    remittanceVolume: 'Fast-growing corridor — Dubai and Abu Dhabi hubs',
    popularCities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman'],
    providers: [
      {
        name: 'Wise',
        fee: '~AED 3.50 + 0.5%',
        feeUSD: 1.2,
        exchangeRateNote: 'Mid-market rate — no markup',
        estimatedKES: '~KES 3,650 per AED 100',
        speed: '1–2 hours',
        deliveryMethods: ['Bank Account', 'M-Pesa'],
        rating: 4.7,
        bestFor: 'Best total value for bank-to-bank transfers',
      },
      {
        name: 'Sendwave',
        fee: 'Zero fees',
        feeUSD: 0,
        exchangeRateNote: '0.5–1.5% margin',
        estimatedKES: '~KES 3,580 per AED 100',
        speed: 'Instant to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account'],
        rating: 4.8,
        bestFor: 'Zero-fee M-Pesa delivery',
        promoNote: 'Available from UAE — popular with Kenyan workers in Gulf',
      },
      {
        name: 'WorldRemit',
        fee: 'AED 4–12',
        feeUSD: 2.5,
        exchangeRateNote: '1.5–2.5% margin',
        estimatedKES: '~KES 3,450 per AED 100',
        speed: 'Minutes to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account', 'Cash Pickup'],
        rating: 4.4,
        bestFor: 'Instant M-Pesa with cash pickup fallback',
      },
      {
        name: 'Remitly',
        fee: 'AED 0–14',
        feeUSD: 2.0,
        exchangeRateNote: '1–2% margin',
        estimatedKES: '~KES 3,500 per AED 100',
        speed: 'Minutes (Express)',
        deliveryMethods: ['M-Pesa', 'Bank Account'],
        rating: 4.5,
        bestFor: 'Speed and reliability for M-Pesa',
      },
      {
        name: 'Al Ansari Exchange',
        fee: 'AED 10–25',
        feeUSD: 4.0,
        exchangeRateNote: '2–3% margin',
        estimatedKES: '~KES 3,300 per AED 100',
        speed: 'Same day',
        deliveryMethods: ['Bank Account', 'Cash Pickup'],
        rating: 4.0,
        bestFor: 'In-person UAE exchange house with wide branch network',
      },
      {
        name: 'Western Union UAE',
        fee: 'AED 15–35',
        feeUSD: 6.5,
        exchangeRateNote: '3–5% margin',
        estimatedKES: '~KES 3,100 per AED 100',
        speed: 'Minutes (cash)',
        deliveryMethods: ['Cash Pickup', 'M-Pesa', 'Bank Account'],
        rating: 3.6,
        bestFor: 'Cash pickup at UAE agent network',
      },
    ],
    howToSteps: [
      'Download Wise or Sendwave from the UAE App Store or Google Play',
      'Verify your Emirates ID or passport for identity verification',
      'Link your UAE bank account (Emirates NBD, FAB, ADCB, etc.) or debit card',
      'Enter the recipient\'s Kenya M-Pesa number or bank account',
      'Confirm the AED amount and the KES amount the recipient will receive',
      'Pay and track — M-Pesa transfers typically arrive within minutes',
      'Keep your transaction reference in case of any delays',
    ],
    taxNote: 'The UAE has no personal income tax. Remittances from the UAE are unrestricted for personal transfers.',
    regulatoryNote: 'Money transfer operators in the UAE are licensed by the Central Bank of the UAE (CBUAE). Always use CBUAE-licensed providers.',
    faqs: [
      {
        q: 'What is the cheapest way to send money from Dubai to Kenya?',
        a: 'Sendwave has zero fees and is widely used by Kenyans in Dubai for M-Pesa transfers. Wise offers the best exchange rate for bank-to-bank transfers. Avoid airport exchange counters — they have the worst rates.',
      },
      {
        q: 'Can I send money from UAE to M-Pesa directly?',
        a: 'Yes — Sendwave, WorldRemit, and Remitly all offer direct delivery to Kenyan M-Pesa numbers from the UAE.',
      },
      {
        q: 'How long does a UAE to Kenya transfer take?',
        a: 'M-Pesa deliveries via Sendwave or WorldRemit are usually instant to 10 minutes. Bank transfers via Wise take 1–2 hours.',
      },
      {
        q: 'Can I use Al Ansari Exchange to send to Kenya?',
        a: 'Yes — Al Ansari is a well-established UAE exchange house that can send to Kenyan bank accounts. However, online providers like Wise or Sendwave typically offer better rates.',
      },
    ],
    tips: [
      'The AED is pegged to USD — USD/KES rates apply, making this a stable corridor',
      'Avoid exchange counters in Dubai Mall or airports — margins are typically 4–6%',
      'For large amounts (above AED 5,000), Wise usually wins on total received KES',
      'Some UAE banks charge outgoing wire fees — check with your bank before SWIFT transfers',
    ],
  },

  // ── Germany ─────────────────────────────────────────────────────────────
  {
    slug: 'germany',
    country: 'Germany',
    countryCode: 'DE',
    currency: 'Euro',
    currencyCode: 'EUR',
    currencySymbol: '€',
    sampleAmount: 100,
    diasporaSize: '~15,000 Kenyans in Germany',
    remittanceVolume: 'Growing corridor — students and professionals',
    popularCities: ['Berlin', 'Munich', 'Frankfurt', 'Hamburg', 'Cologne', 'Stuttgart'],
    providers: [
      {
        name: 'Wise',
        fee: '~€0.70 + 0.47%',
        feeUSD: 1.1,
        exchangeRateNote: 'Mid-market rate — no markup',
        estimatedKES: '~KES 14,200 per €100 (best rate)',
        speed: '2–24 hours',
        deliveryMethods: ['Bank Account', 'M-Pesa'],
        rating: 4.8,
        bestFor: 'Best exchange rate — popular among Kenyan students in Germany',
      },
      {
        name: 'Sendwave',
        fee: 'Zero fees',
        feeUSD: 0,
        exchangeRateNote: '0.5–1.5% margin',
        estimatedKES: '~KES 13,900 per €100',
        speed: 'Instant to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account'],
        rating: 4.7,
        bestFor: 'Zero fees for M-Pesa delivery from Germany',
      },
      {
        name: 'Remitly',
        fee: '€0–€3.99',
        feeUSD: 2.5,
        exchangeRateNote: '1–2% margin',
        estimatedKES: '~KES 13,700 per €100',
        speed: 'Minutes (Express)',
        deliveryMethods: ['M-Pesa', 'Bank Account'],
        rating: 4.5,
        bestFor: 'Speed for urgent transfers',
      },
      {
        name: 'WorldRemit',
        fee: '€1.99–€4.99',
        feeUSD: 3.5,
        exchangeRateNote: '1.5–2.5% margin',
        estimatedKES: '~KES 13,500 per €100',
        speed: 'Minutes to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account', 'Airtime Top-Up'],
        rating: 4.3,
        bestFor: 'Airtime top-up and reliable M-Pesa',
      },
      {
        name: 'Western Union Germany',
        fee: '€3.90–€12',
        feeUSD: 7.0,
        exchangeRateNote: '3–5% margin',
        estimatedKES: '~KES 12,600 per €100',
        speed: 'Minutes to hours',
        deliveryMethods: ['Cash Pickup', 'M-Pesa', 'Bank Account'],
        rating: 3.6,
        bestFor: 'Cash pickup fallback option',
      },
    ],
    howToSteps: [
      'Download Wise or Sendwave from the German App Store or Google Play',
      'Register with your German address and verify via Ausweis (ID card) or passport',
      'Connect your German bank account (IBAN/BIC) or debit card',
      'Enter the recipient\'s Kenyan M-Pesa number or bank account',
      'Review the EUR amount and the KES amount to be received',
      'Confirm and pay — SEPA transfers fund within hours, card payments are faster',
      'You will receive email/SMS confirmation when the transfer is delivered',
    ],
    taxNote: 'No German tax on personal remittances. Gifts above €20,000 to non-EU recipients may need to be declared to the German tax office (Finanzamt) for gift tax purposes.',
    regulatoryNote: 'All providers listed are licensed by BaFin (Germany\'s financial regulator) or passported from the UK/EU. Always use BaFin-authorised services.',
    faqs: [
      {
        q: 'What is the best way to send money from Germany to Kenya?',
        a: 'Wise is the top choice for students and professionals in Germany — it uses the mid-market rate with minimal fees. Sendwave is best for zero-fee M-Pesa transfers.',
      },
      {
        q: 'Can I send from a German bank account directly to Kenya?',
        a: 'Not easily via direct SWIFT — the fees are high. Use Wise instead, which accepts SEPA bank transfers from any German bank and forwards to Kenya at near mid-market rates.',
      },
      {
        q: 'How long does a Germany to Kenya bank transfer take?',
        a: 'Via Wise: 2–24 hours after SEPA payment clears. Via WorldRemit or Sendwave to M-Pesa: minutes. Direct bank SWIFT: 2–4 business days.',
      },
      {
        q: 'I am a Kenyan student in Germany — what is the cheapest way to send money home?',
        a: 'Wise has the best exchange rate and very low fees — ideal for students sending monthly support. For small, urgent amounts, Sendwave is free and instant.',
      },
    ],
    tips: [
      'SEPA transfers are free from German banks — always fund Wise via bank transfer, not card, to avoid card fees',
      'Set up a recurring Wise transfer for monthly family support — takes 5 minutes to automate',
      'The EUR/KES rate fluctuates — use Wise\'s rate alert to send when the rate is favourable',
      'For Kenyans in Germany on student visas, Wise does not restrict remittances — full service available',
    ],
  },

  // ── Canada ───────────────────────────────────────────────────────────────
  {
    slug: 'canada',
    country: 'Canada',
    countryCode: 'CA',
    currency: 'Canadian Dollar',
    currencyCode: 'CAD',
    currencySymbol: 'CA$',
    sampleAmount: 100,
    diasporaSize: '~40,000 Kenyans in Canada',
    remittanceVolume: 'Growing fast — Toronto and Ottawa hubs',
    popularCities: ['Toronto', 'Ottawa', 'Vancouver', 'Calgary', 'Edmonton'],
    providers: [
      {
        name: 'Sendwave',
        fee: 'Zero fees',
        feeUSD: 0,
        exchangeRateNote: '0.5–1.5% margin',
        estimatedKES: '~KES 9,800 per CA$100',
        speed: 'Instant to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account'],
        rating: 4.8,
        bestFor: 'Zero-fee M-Pesa delivery from Canada',
      },
      {
        name: 'Wise',
        fee: '~CA$1.30 + 0.47%',
        feeUSD: 1.2,
        exchangeRateNote: 'Mid-market rate',
        estimatedKES: '~KES 10,000 per CA$100',
        speed: '2–24 hours',
        deliveryMethods: ['Bank Account', 'M-Pesa'],
        rating: 4.7,
        bestFor: 'Best rate for bank account delivery',
      },
      {
        name: 'Remitly',
        fee: 'CA$0–$3.99',
        feeUSD: 2.0,
        exchangeRateNote: '1–2% margin',
        estimatedKES: '~KES 9,600 per CA$100',
        speed: 'Minutes to hours',
        deliveryMethods: ['M-Pesa', 'Bank Account'],
        rating: 4.5,
        bestFor: 'First transfer promo deals',
      },
      {
        name: 'WorldRemit',
        fee: 'CA$1.99–$5.99',
        feeUSD: 3.5,
        exchangeRateNote: '1.5–2.5% margin',
        estimatedKES: '~KES 9,400 per CA$100',
        speed: 'Minutes to M-Pesa',
        deliveryMethods: ['M-Pesa', 'Bank Account', 'Airtime'],
        rating: 4.3,
        bestFor: 'Airtime and M-Pesa',
      },
    ],
    howToSteps: [
      'Download Sendwave or Wise from the Canadian App Store or Google Play',
      'Verify your identity with a Canadian ID (driver\'s licence or passport)',
      'Connect your Canadian bank account or Interac debit card',
      'Enter the recipient\'s Kenyan M-Pesa number or bank details',
      'Confirm the CAD and KES amounts',
      'Pay and track — M-Pesa arrivals are typically instant',
    ],
    taxNote: 'No Canadian tax on personal remittances. Gift tax rules are different in Canada than the US — consult an accountant for large regular transfers.',
    regulatoryNote: 'Money service businesses in Canada are registered with FINTRAC. Always use FINTRAC-registered providers.',
    faqs: [
      {
        q: 'What is the cheapest way to send money from Canada to Kenya?',
        a: 'Sendwave charges zero fees from Canada and delivers to M-Pesa instantly. For larger amounts, Wise offers the mid-market rate with minimal fees.',
      },
      {
        q: 'Can I use Interac e-Transfer to fund a remittance to Kenya?',
        a: 'Not directly — but some Canadian providers accept Interac debit cards. Wise accepts Canadian bank account funding via EFT which is essentially free.',
      },
    ],
    tips: [
      'CAD/KES rates are influenced by the CAD/USD rate — send when the Canadian dollar is strong',
      'Sendwave has no fees and is the most popular choice for Toronto\'s Kenyan community',
      'Avoid major Canadian bank wire transfers to Kenya — fees of CA$25–50 plus poor exchange rates',
    ],
  },
]
